#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

dokku_app_docker_args() {
  local STDIN=$(cat)
  local APP="$1"

  local DOKKU_APP_USER=$(config_get $APP DOKKU_APP_USER || true)

  if [[ -n "$DOKKU_APP_USER" ]]; then
    local docker_args="$STDIN --env=USER=${DOKKU_APP_USER}"
  else
    local docker_args="$STDIN"
  fi

  echo -n "$docker_args"
}

dokku_app_docker_args "$@"
