#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"

get_app_user() {
  local APP="$1"; local IMAGE=$(get_app_image_name $APP)

  local DOKKU_APP_USER=$(config_get $APP DOKKU_APP_USER)
  [[ -z "$DOKKU_APP_USER" ]] && local DOKKU_APP_USER=$(docker run -i --rm $IMAGE /bin/bash -c "stat -c %U /app")

  echo $DOKKU_APP_USER
}
