#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
# shellcheck disable=SC1090
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

dokku_app_user_pre_deploy_trigger() {
  local desc="dokku app user pre-deploy trigger"
  local APP="$1"; local IMAGE_TAG="$2"; local IMAGE; local DOCKER_ARGS
  local DOKKU_APP_USER; local APP_PATHS; local CONTAINER_PATHS
  IMAGE=$(get_app_image_name "$APP" "$IMAGE_TAG")
  DOKKU_APP_USER=$(config_get "$APP" DOKKU_APP_USER || true)
  APP_PATHS=$(dokku --quiet storage:list "$APP" || true)
  if [[ -n "$APP_PATHS" ]]; then
    CONTAINER_PATHS=$(echo "$APP_PATHS" | awk -F ':' '{ print $2 }' | xargs)
    DOCKER_ARGS=$(: | plugn trigger docker-args-deploy "$APP" "$IMAGE_TAG" | xargs)
    # strip --restart args from DOCKER_ARGS
    DOCKER_ARGS=$(sed -e "s/--restart=[[:graph:]]\+[[:blank:]]\?//g" <<< "$DOCKER_ARGS")
  fi

  if [[ -n "$DOKKU_APP_USER" ]] && [[ -n "$CONTAINER_PATHS" ]]; then
    # shellcheck disable=SC2086
    docker run $DOKKU_GLOBAL_RUN_ARGS $DOCKER_ARGS $IMAGE /bin/bash -c "find $CONTAINER_PATHS -not -user $DOKKU_APP_USER -print0 | xargs -0 -r chown -R $DOKKU_APP_USER" || true
  fi
}

dokku_app_user_pre_deploy_trigger "$@"
